#!/usr/bin/env bash
set -euo pipefail

WORKDIR="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$WORKDIR"

DENYLIST=(
  "MINERVA"
  "BUSINESS PLUS"
  "/analyze"
  "Generated by MINERVA"
)

EXTRA_LIST="$WORKDIR/scripts/guardrails/denylist_extra.txt"
if [ -f "$EXTRA_LIST" ]; then
  while IFS= read -r line; do
    [ -z "$line" ] && continue
    DENYLIST+=("$line")
  done < "$EXTRA_LIST"
fi

hits=0
for pat in "${DENYLIST[@]}"; do
  if rg -q --fixed-strings \
    --glob '!target/**' \
    --glob '!artifacts/**' \
    --glob '!yunitrack_src_latest.tgz' \
    --glob '!scripts/guardrails/**' \
    "$pat" "$WORKDIR"; then
    hits=$((hits + 1))
  fi
done

if [ "$hits" -gt 0 ]; then
  echo "SECURITY: DENYLIST_HIT count=$hits"
  exit 1
fi

echo "SECURITY: DENYLIST_PASS count=0"
